# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 125b9507ea1d5eb4066dc21e64eec410cf10161a5bea7c4fef0fc59da2d4578e5f1fd6eeb3a8ab198d8ea80d5e9834ff36861221c838f3b79955c621088d4df5

test:
  secret_key_base: e0bdf6d82e3d2d5ed221559c627c30989e77cfcc6c527587f892c69f1a18e80e468d8d98603a6470f561044a26d004080987e8be588c1b55fccb44ea1a4113ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
